import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import setupRouter from "./setup.js";
import authRouter from "./auth.js";
import branchesRouter from "./branches.js";
import departmentsRouter from "./departments.js";
import shiftsRouter from "./shifts.js";
import employeesRouter from "./employees.js";
import attendanceRouter from "./attendance.js";
import leavesRouter from "./leaves.js";
import reportsRouter from "./reports.js";
import settingsRouter from "./settings.js";
import superAdminRouter from "./super-admin.js";
import messagesRouter from "./messages.js";
import securityRouter from "./security.js";
import payrollRouter from "./payroll.js";
import preferencesRouter from "./preferences.js";
import subscriptionsRouter from "./subscriptions.js";
import monitoringRouter from "./monitoring.js";
import notificationsRouter from "./notifications.js";
import companyAlertsRouter from "./company-alerts.js";
import profileRouter from "./profile.js";
import auditLogsRouter from "./audit-logs.js";
import documentsRouter from "./documents.js";
import loansRouter from "./loans.js";
import userNotificationsRouter from "./user-notifications.js";
import calendarRouter from "./calendar.js";
import performanceRouter from "./performance.js";
import knowledgeRouter from "./knowledge.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/setup", setupRouter);
router.use("/auth", authRouter);
router.use("/security", securityRouter);
router.use("/super-admin", superAdminRouter);
router.use("/super-admin", subscriptionsRouter);
router.use("/super-admin/monitoring", monitoringRouter);
router.use("/super-admin/notifications", notificationsRouter);
router.use("/company/alerts", companyAlertsRouter);
router.use("/branches", branchesRouter);
router.use("/departments", departmentsRouter);
router.use("/shifts", shiftsRouter);
router.use("/employees", employeesRouter);
router.use("/attendance", attendanceRouter);
router.use("/leaves", leavesRouter);
router.use("/reports", reportsRouter);
router.use("/settings", settingsRouter);
router.use("/messages", messagesRouter);
router.use("/payroll", payrollRouter);
router.use("/preferences", preferencesRouter);
router.use("/profile", profileRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/documents", documentsRouter);
router.use("/loans", loansRouter);
router.use("/user-notifications", userNotificationsRouter);
router.use("/calendar", calendarRouter);
router.use("/performance", performanceRouter);
router.use("/knowledge", knowledgeRouter);

export default router;
