// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hr-dashboard/AuroraGlass.tsx": () => import("../components/mockups/hr-dashboard/AuroraGlass.tsx"),
  "./components/mockups/hr-dashboard/CyberpunkNeon.tsx": () => import("../components/mockups/hr-dashboard/CyberpunkNeon.tsx")
};
