// ─── Shared Super-Admin i18n + Theme utilities ─────────────────────────────
// Each super-admin page imports { SA_T, useSAColors } from this file.

export const SA_T = {
  ar: {
    // ── Navigation / Header ─────────────────────────────────────────────────
    dashboardTitle:       "لوحة التحكم الرئيسية",
    manageAllCompanies:   "إدارة جميع الشركات",
    monitoring:           "المراقبة",
    subscriptions:        "الاشتراكات",
    notifications:        "الإشعارات",
    security:             "الأمان",
    signOut:              "خروج",
    back:                 "رجوع",
    refresh:              "تحديث",
    loading:              "جاري التحميل...",
    saving:               "جاري الحفظ...",
    noData:               "لا توجد بيانات",
    save:                 "حفظ",
    cancel:               "إلغاء",
    deleteBtn:            "حذف",
    edit:                 "تعديل",
    view:                 "عرض",
    close:                "إغلاق",
    yes:                  "نعم",
    no:                   "لا",

    // ── Common columns ──────────────────────────────────────────────────────
    companyCol:           "الشركة",
    statusCol:            "الحالة",
    dateCol:              "التاريخ",
    timeCol:              "الوقت",
    actionCol:            "العملية",
    userCol:              "المستخدم",
    typeCol:              "النوع",
    amountCol:            "المبلغ",
    ipCol:                "IP",
    resourceCol:          "المورد",
    actionsCol:           "الإجراءات",

    // ── Super Admin Dashboard ───────────────────────────────────────────────
    totalCompanies:       "إجمالي الشركات",
    activeCompanies:      "شركات نشطة",
    suspendedCompanies:   "شركات موقوفة",
    totalEmployees:       "إجمالي الموظفين",
    companiesTab:         "الشركات",
    backupsTab:           "النسخ الاحتياطية",
    createCompany:        "إنشاء شركة",
    editCompany:          "تعديل الشركة",
    deleteCompany:        "حذف الشركة",
    companyName:          "اسم الشركة",
    companyAddress:       "العنوان",
    companyPhone:         "الهاتف",
    companyEmail:         "البريد الإلكتروني",
    adminUsername:        "مستخدم المدير",
    adminPassword:        "كلمة مرور المدير",
    confirmDeleteCompany: "هل تريد حذف هذه الشركة وجميع بياناتها؟",
    noCompanies:          "لا توجد شركات",
    employees:            "موظف",
    active:               "نشط",
    suspended:            "موقوف",
    activate:             "تفعيل",
    suspend:              "إيقاف",
    noEmployees:          "لا يوجد موظفون",
    changePassword:       "تغيير كلمة المرور",
    newPassword:          "كلمة المرور الجديدة",
    allCompanies:         "كل الشركات",
    backupFor:            "نسخة لـ",
    fullSystem:           "النظام كامل",
    createBackup:         "إنشاء نسخة",
    download:             "تنزيل",
    noBackups:            "لا توجد نسخ احتياطية",

    // ── Monitoring ──────────────────────────────────────────────────────────
    systemMonitoring:     "مركز مراقبة النظام",
    autoUpdate5s:         "يتحدث كل 5 ثوان",
    lastUpdate:           "آخر تحديث",
    serverStatus:         "حالة الخادم",
    avgResponse:          "الرد المتوسط",
    activeSessions:       "جلسات نشطة",
    recentErrors1h:       "أخطاء أخيرة (ساعة)",
    uptimeLabel:          "وقت التشغيل",
    online:               "متصل",
    offline:              "غير متصل",
    cpuLabel:             "المعالج CPU",
    ramLabel:             "الذاكرة RAM",
    coresLabel:           "نواة",
    resourceHistory:      "سجل الموارد",
    requestRateChart:     "معدل الطلبات (آخر 10 دقائق)",
    databaseLabel:        "قاعدة البيانات",
    apiPerformance:       "أداء الـ API",
    recentAuditLogs:      "سجل العمليات الأخيرة",
    postgresConnected:    "PostgreSQL متصل",
    dbUnavailable:        "قاعدة البيانات غير متاحة",
    avgResponseCard:      "متوسط الرد",
    reqPerMin:            "طلب/دقيقة",
    totalRequests:        "إجمالي الطلبات",
    succeeded:            "✓ نجح",
    failed:               "✗ فشل",
    noLogs:               "لا يوجد سجلات",
    days:                 "ي",
    hours:                "س",
    minutes:              "د",

    // ── Subscriptions ───────────────────────────────────────────────────────
    subscriptionsSystem:  "نظام الاشتراكات",
    managePlansInvoices:  "إدارة خطط وفواتير الشركات",
    overviewTab:          "نظرة عامة",
    plansTab:             "الخطط",
    paymentsTab:          "المدفوعات",
    activeSubsCount:      "اشتراكات نشطة",
    expiredSubsCount:     "اشتراكات منتهية",
    expiresIn7Days:       "تنتهي خلال 7 أيام",
    totalRevenueLabel:    "إجمالي الإيرادات",
    companySubStatus:     "حالة اشتراكات الشركات",
    planCol:              "الخطة",
    expiryDateCol:        "تاريخ الانتهاء",
    daysRemainingCol:     "الأيام المتبقية",
    assignPlanBtn:        "تعيين خطة",
    extendBtn:            "تمديد",
    invoicesBtn:          "الفواتير",
    planMonthly:          "شهري",
    planSemiAnnual:       "نصف سنوي",
    planAnnual:           "سنوي",
    planLifetime:         "مدى الحياة",
    lifetimeDisplay:      "∞ مدى الحياة",
    statusActive:         "نشط",
    statusExpired:        "منتهي",
    statusCancelled:      "ملغي",
    statusTrial:          "تجريبي",
    noSubscription:       "لا يوجد",
    paymentHistoryFull:   "سجل المدفوعات الكامل",
    invoiceNoCol:         "رقم الفاتورة",
    paymentMethodCol:     "طريقة الدفع",
    viewInvoiceBtn:       "فاتورة",
    paidStatus:           "مدفوع",
    assignSubscription:   "تعيين خطة اشتراك",
    selectPlan:           "اختر خطة",
    startDateLabel:       "تاريخ البدء",
    endDateLabel:         "تاريخ الانتهاء",
    autoRenewLabel:       "تجديد تلقائي",
    activateSubscription: "تفعيل الاشتراك",
    extendSubscription:   "تمديد الاشتراك — ",
    monthsLabel:          "عدد الأشهر",
    amountPaidLabel:      "المبلغ المدفوع ($)",
    paymentMethodSel:     "طريقة الدفع",
    extending:            "جاري التمديد...",
    manualMethod:         "يدوي",
    cashMethod:           "نقداً",
    transferMethod:       "تحويل بنكي",
    cardMethod:           "بطاقة",
    taxInvoice:           "فاتورة ضريبية",
    attendanceSysName:    "نظام إدارة الحضور والانصراف",
    invoiceNumberLabel:   "رقم الفاتورة",
    issuedTo:             "مُصدر إلى",
    serviceCol:           "الخدمة",
    totalAmount:          "الإجمالي",
    printDownloadPDF:     "طباعة / تنزيل PDF",
    invoicesFor:          "فواتير",
    noInvoicesCompany:    "لا توجد فواتير لهذه الشركة",
    mostValuable:         "الأكثر قيمة",
    employeesLimit:       "موظف",
    branchesLimit:        "فرع",
    storageLabel:         "GB تخزين",
    editPlanTitle:        "تعديل الخطة — ",
    planNameLabel:        "اسم الخطة",
    priceUSD:             "💰 السعر (USD)",
    maxEmployeesLabel:    "عدد الموظفين",
    maxBranchesLabel:     "عدد الفروع",
    storageGBLabel:       "التخزين (GB)",
    featuresTextarea:     "المميزات (سطر لكل ميزة)",
    saveChanges:          "حفظ التغييرات",
    changesSaved:         "تم حفظ التغييرات بنجاح",
    subscriptionActivated: "تم تفعيل الاشتراك بنجاح",
    subscriptionExtended:  "تم تمديد الاشتراك بنجاح",
    perMonth:             "/شهر",
    per6Months:           "/6 أشهر",
    perYear:              "/سنة",
    perLifetime:          "/مرة",
    unlimited:            "غير محدود",

    // ── Subscriptions (aliases & extras) ────────────────────────────
    bestValue:            "الأكثر قيمة",
    once:                 "مرة",
    month:                "شهر",
    sixMonths:            "6 أشهر",
    year:                 "سنة",
    employeeUnit:         "موظف",
    branchUnit:           "فرع",
    storageUnit:          "تخزين",
    statusDisabled:       "معطل",
    editBtn:              "تعديل",
    allPaymentsRecord:    "سجل المدفوعات الكامل",
    invoiceUnit:          "فاتورة",
    invoiceNumberCol:     "رقم الفاتورة",
    invoiceBtn:           "فاتورة",
    assignPlanTitle:      "تعيين خطة اشتراك",
    planLabel:            "الخطة",
    startDate:            "تاريخ البدء",
    endDate:              "تاريخ الانتهاء",
    autoRenew:            "تجديد تلقائي",
    extendSubTitle:       "تمديد الاشتراك",
    monthsCount:          "عدد الأشهر",
    amountPaid:           "المبلغ المدفوع ($)",
    paymentMethod:        "طريقة الدفع",
    paymentMethods:       { manual: "يدوي", cash: "نقداً", transfer: "تحويل بنكي", card: "بطاقة" },
    attendanceSystem:     "نظام إدارة الحضور والانصراف",
    subscriptionOf:       "اشتراك",
    total:                "الإجمالي",
    printDownloadPdf:     "طباعة / تنزيل PDF",
    priceLabel:           "السعر (USD)",
    maxEmployees:         "عدد الموظفين",
    maxBranches:          "عدد الفروع",
    storageGbLabel:       "التخزين (GB)",
    featuresLabel:        "المميزات (سطر لكل ميزة)",
    companyInvoices:      "فواتير",
    noInvoicesForCompany: "لا توجد فواتير لهذه الشركة",
    viewBtn:              "عرض",

    // ── Notifications ───────────────────────────────────────────────────────
    notificationsCenter:  "مركز الإشعارات",
    unreadCountSuffix:    "إشعار غير مقروء",
    readAllBtn:           "قراءة الكل",
    clearReadBtn:         "مسح المقروء",
    allFilter:            "الكل",
    unreadFilter:         "غير مقروء",
    warningsFilter:       "تحذيرات",
    errorsFilter:         "أخطاء",
    successFilter:        "نجاح",
    noNotifications:      "لا توجد إشعارات",
    markAsReadBtn:        "تحديد كمقروء",
    infoSev:              "معلومة",
    warningSev:           "تحذير",
    errorSev:             "خطأ",
    successSev:           "نجاح",
    confirmClearRead:     "حذف كل الإشعارات المقروءة؟",
    allReadDone:          "تم تحديد الكل كمقروء",
    clearReadDone:        "تم مسح الإشعارات المقروءة",

    // ── Security ────────────────────────────────────────────────────────────
    securityCenter:       "مركز الأمان",
    securitySubtitle:     "مراقبة الأمان والجلسات",
    openEvents:           "أحداث مفتوحة",
    failedLogins24h:      "محاولات فاشلة (24س)",
    lockedAccounts:       "حسابات مقفلة",
    activeSessionsLabel:  "جلسات نشطة",
    securityEvents:       "أحداث الأمان",
    auditLogs:            "سجل العمليات",
    sessions:             "الجلسات",
    lockedAccountsTab:    "حسابات مقفلة",
    overviewTab2:         "نظرة عامة",
    resolve:              "حل",
    unlock:               "فتح الحساب",
    terminate:            "إنهاء",
    lowSev:               "منخفض",
    mediumSev:            "متوسط",
    highSev:              "عالي",
    criticalSev:          "حرج",
    allSeverities:        "كل الخطورات",
    noEvents:             "لا توجد أحداث أمنية",
    noAuditLogs:          "لا توجد سجلات",
    noSessions:           "لا توجد جلسات نشطة",
    noLockedAccounts:     "لا توجد حسابات مقفلة",
    resolved:             "محلول",
    unresolved:           "مفتوح",
    loginAttempts:        "محاولات تسجيل",
    successful:           "ناجحة",
    failedLabel:          "فاشلة",
    uniqueIPs:            "IPs فريدة",
    last24h:              "آخر 24 ساعة",
    topIPs:               "أكثر IPs اتصالاً",
    recentFails:          "آخر محاولات فاشلة",
    device:               "الجهاز",
    lastActive:           "آخر نشاط",
    attempts:             "محاولة",
    failures:             "فاشلة",

    // ── Security extra ───────────────────────────────────────────────────────
    openEvents7d:         "حوادث مفتوحة (7 أيام)",
    lockedAccountsLabel:  "حسابات مقفلة",
    activeSessions1h:     "جلسات نشطة (1س)",
    activeProtectionLayers: "طبقات الحماية المفعّلة",
    protectionFeatures: [
      "تشفير كلمات المرور (bcrypt 12 rounds)",
      "حظر IP بعد 20 محاولة فاشلة",
      "قفل الحساب بعد 5 محاولات",
      "Security Headers (Helmet.js)",
      "Rate Limiting (500 req/15min)",
      "CSRF Protection (SameSite + Origin Check)",
      "Session Expiration (8 ساعات)",
      "Audit Log لكل العمليات",
      "Tenant Isolation (company_id)",
      "SQL Injection Prevention (Drizzle ORM)",
      "XSS Prevention (Input Sanitization)",
      "Device Tracking & Session Management",
    ],
    loginStats:           "إحصائيات تسجيل الدخول",
    successfulTotal:      "ناجح (إجمالي)",
    failedTotal:          "فاشل (إجمالي)",
    topIPs24h:            "أعلى IPs بمحاولات الدخول (24س)",
    requests:             "طلب",
    noRecords:            "لا توجد سجلات",
    successLabel:         "نجاح",
    resolveEvent:         "حل الحادثة",
    terminateSession:     "إنهاء",
    unlockAccount:        "فتح القفل",
    failedAttempts:       "محاولة فاشلة",
    lockedUntil:          "مقفل حتى",
    activeSessions2:      "الجلسات النشطة",
    lockedAccountsTitle:  "الحسابات المقفلة",
    superAdmin:           "سوبر ادمن",
    roleAdmin:            "مدير",
    roleManager:          "مشرف",
    roleEmployee:         "موظف",
    password:             "كلمة المرور",
    supportCenter:        "مركز الدعم",
    roleCol:              "الدور",
    downloadBackup:       "تنزيل",
    deleteBackup:         "حذف",
    confirmDelete:        "تأكيد الحذف",
    confirmDeleteMsg:     "هل أنت متأكد من حذف",
    confirmDeleteData:    "سيتم حذف جميع البيانات المرتبطة بها.",
    toggleStatus:         "تفعيل/إيقاف",
    editLabel:            "تعديل",
    deleteLabel:          "حذف",
    addNewCompany:        "إضافة شركة جديدة",
    companyAdminData:     "بيانات مدير الشركة",
    fullName:             "الاسم الكامل *",
    createCompanySubmit:  "إنشاء الشركة",
    newPasswordLabel:     "كلمة المرور الجديدة",
    changePasswordTitle:  "تغيير كلمة مرور",
    changePasswordSubmit: "تغيير",
  },

  en: {
    // ── Navigation / Header ─────────────────────────────────────────────────
    dashboardTitle:       "Super Admin Panel",
    manageAllCompanies:   "Manage All Companies",
    monitoring:           "Monitoring",
    subscriptions:        "Subscriptions",
    notifications:        "Notifications",
    security:             "Security",
    signOut:              "Sign Out",
    back:                 "Back",
    refresh:              "Refresh",
    loading:              "Loading...",
    saving:               "Saving...",
    noData:               "No data",
    save:                 "Save",
    cancel:               "Cancel",
    deleteBtn:            "Delete",
    edit:                 "Edit",
    view:                 "View",
    close:                "Close",
    yes:                  "Yes",
    no:                   "No",

    // ── Common columns ──────────────────────────────────────────────────────
    companyCol:           "Company",
    statusCol:            "Status",
    dateCol:              "Date",
    timeCol:              "Time",
    actionCol:            "Action",
    userCol:              "User",
    typeCol:              "Type",
    amountCol:            "Amount",
    ipCol:                "IP",
    resourceCol:          "Resource",
    actionsCol:           "Actions",

    // ── Super Admin Dashboard ───────────────────────────────────────────────
    totalCompanies:       "Total Companies",
    activeCompanies:      "Active Companies",
    suspendedCompanies:   "Suspended Companies",
    totalEmployees:       "Total Employees",
    companiesTab:         "Companies",
    backupsTab:           "Backups",
    createCompany:        "Create Company",
    editCompany:          "Edit Company",
    deleteCompany:        "Delete Company",
    companyName:          "Company Name",
    companyAddress:       "Address",
    companyPhone:         "Phone",
    companyEmail:         "Email",
    adminUsername:        "Admin Username",
    adminPassword:        "Admin Password",
    confirmDeleteCompany: "Delete this company and all its data?",
    noCompanies:          "No companies found",
    employees:            "employees",
    active:               "Active",
    suspended:            "Suspended",
    activate:             "Activate",
    suspend:              "Suspend",
    noEmployees:          "No employees",
    changePassword:       "Change Password",
    newPassword:          "New Password",
    allCompanies:         "All Companies",
    backupFor:            "Backup for",
    fullSystem:           "Full System",
    createBackup:         "Create Backup",
    download:             "Download",
    noBackups:            "No backups found",

    // ── Monitoring ──────────────────────────────────────────────────────────
    systemMonitoring:     "System Monitoring Center",
    autoUpdate5s:         "updates every 5s",
    lastUpdate:           "Last update",
    serverStatus:         "Server Status",
    avgResponse:          "Avg. Response",
    activeSessions:       "Active Sessions",
    recentErrors1h:       "Recent Errors (1h)",
    uptimeLabel:          "Uptime",
    online:               "Online",
    offline:              "Offline",
    cpuLabel:             "CPU Usage",
    ramLabel:             "RAM Usage",
    coresLabel:           "cores",
    resourceHistory:      "Resource History",
    requestRateChart:     "Request Rate (last 10 min)",
    databaseLabel:        "Database",
    apiPerformance:       "API Performance",
    recentAuditLogs:      "Recent Audit Logs",
    postgresConnected:    "PostgreSQL Connected",
    dbUnavailable:        "Database Unavailable",
    avgResponseCard:      "Avg. Response",
    reqPerMin:            "req/min",
    totalRequests:        "total requests",
    succeeded:            "✓ Success",
    failed:               "✗ Failed",
    noLogs:               "No logs found",
    days:                 "d",
    hours:                "h",
    minutes:              "m",

    // ── Subscriptions ───────────────────────────────────────────────────────
    subscriptionsSystem:  "Subscriptions System",
    managePlansInvoices:  "Manage company plans & invoices",
    overviewTab:          "Overview",
    plansTab:             "Plans",
    paymentsTab:          "Payments",
    activeSubsCount:      "Active Subscriptions",
    expiredSubsCount:     "Expired Subscriptions",
    expiresIn7Days:       "Expiring in 7 Days",
    totalRevenueLabel:    "Total Revenue",
    companySubStatus:     "Company Subscription Status",
    planCol:              "Plan",
    expiryDateCol:        "Expiry Date",
    daysRemainingCol:     "Days Remaining",
    assignPlanBtn:        "Assign Plan",
    extendBtn:            "Extend",
    invoicesBtn:          "Invoices",
    planMonthly:          "Monthly",
    planSemiAnnual:       "Semi-Annual",
    planAnnual:           "Annual",
    planLifetime:         "Lifetime",
    lifetimeDisplay:      "∞ Lifetime",
    statusActive:         "Active",
    statusExpired:        "Expired",
    statusCancelled:      "Cancelled",
    statusTrial:          "Trial",
    noSubscription:       "None",
    paymentHistoryFull:   "Full Payment History",
    invoiceNoCol:         "Invoice No.",
    paymentMethodCol:     "Payment Method",
    viewInvoiceBtn:       "Invoice",
    paidStatus:           "Paid",
    assignSubscription:   "Assign Subscription Plan",
    selectPlan:           "Select a plan",
    startDateLabel:       "Start Date",
    endDateLabel:         "End Date",
    autoRenewLabel:       "Auto Renew",
    activateSubscription: "Activate Subscription",
    extendSubscription:   "Extend Subscription — ",
    monthsLabel:          "Months",
    amountPaidLabel:      "Amount Paid ($)",
    paymentMethodSel:     "Payment Method",
    extending:            "Extending...",
    manualMethod:         "Manual",
    cashMethod:           "Cash",
    transferMethod:       "Bank Transfer",
    cardMethod:           "Card",
    taxInvoice:           "Tax Invoice",
    attendanceSysName:    "Attendance Management System",
    invoiceNumberLabel:   "Invoice Number",
    issuedTo:             "Issued To",
    serviceCol:           "Service",
    totalAmount:          "Total",
    printDownloadPDF:     "Print / Download PDF",
    invoicesFor:          "Invoices for",
    noInvoicesCompany:    "No invoices for this company",
    mostValuable:         "Best Value",
    employeesLimit:       "employees",
    branchesLimit:        "branches",
    storageLabel:         "GB storage",
    editPlanTitle:        "Edit Plan — ",
    planNameLabel:        "Plan Name",
    priceUSD:             "💰 Price (USD)",
    maxEmployeesLabel:    "Max Employees",
    maxBranchesLabel:     "Max Branches",
    storageGBLabel:       "Storage (GB)",
    featuresTextarea:     "Features (one per line)",
    saveChanges:          "Save Changes",
    changesSaved:         "Changes saved successfully",
    subscriptionActivated: "Subscription activated",
    subscriptionExtended:  "Subscription extended",
    perMonth:             "/mo",
    per6Months:           "/6mo",
    perYear:              "/yr",
    perLifetime:          "/once",
    unlimited:            "Unlimited",

    // ── Subscriptions (aliases & extras) ────────────────────────────
    bestValue:            "Best Value",
    once:                 "once",
    month:                "Month",
    sixMonths:            "6 Months",
    year:                 "Year",
    employeeUnit:         "employees",
    branchUnit:           "branches",
    storageUnit:          "storage",
    statusDisabled:       "Disabled",
    editBtn:              "Edit",
    allPaymentsRecord:    "Full Payment History",
    invoiceUnit:          "invoice",
    invoiceNumberCol:     "Invoice No.",
    invoiceBtn:           "Invoice",
    assignPlanTitle:      "Assign Subscription Plan",
    planLabel:            "Plan",
    startDate:            "Start Date",
    endDate:              "End Date",
    autoRenew:            "Auto Renew",
    extendSubTitle:       "Extend Subscription",
    monthsCount:          "Months",
    amountPaid:           "Amount Paid ($)",
    paymentMethod:        "Payment Method",
    paymentMethods:       { manual: "Manual", cash: "Cash", transfer: "Bank Transfer", card: "Card" },
    attendanceSystem:     "Attendance Management System",
    subscriptionOf:       "Subscription:",
    total:                "Total",
    printDownloadPdf:     "Print / Download PDF",
    priceLabel:           "Price (USD)",
    maxEmployees:         "Max Employees",
    maxBranches:          "Max Branches",
    storageGbLabel:       "Storage (GB)",
    featuresLabel:        "Features (one per line)",
    companyInvoices:      "Invoices for",
    noInvoicesForCompany: "No invoices for this company",
    viewBtn:              "View",

    // ── Notifications ───────────────────────────────────────────────────────
    notificationsCenter:  "Notifications Center",
    unreadCountSuffix:    "unread",
    readAllBtn:           "Mark All Read",
    clearReadBtn:         "Clear Read",
    allFilter:            "All",
    unreadFilter:         "Unread",
    warningsFilter:       "Warnings",
    errorsFilter:         "Errors",
    successFilter:        "Success",
    noNotifications:      "No notifications",
    markAsReadBtn:        "Mark as Read",
    infoSev:              "Info",
    warningSev:           "Warning",
    errorSev:             "Error",
    successSev:           "Success",
    confirmClearRead:     "Delete all read notifications?",
    allReadDone:          "All marked as read",
    clearReadDone:        "Read notifications cleared",

    // ── Security ────────────────────────────────────────────────────────────
    securityCenter:       "Security Center",
    securitySubtitle:     "Monitor security & sessions",
    openEvents:           "Open Events",
    failedLogins24h:      "Failed Logins (24h)",
    lockedAccounts:       "Locked Accounts",
    activeSessionsLabel:  "Active Sessions",
    securityEvents:       "Security Events",
    auditLogs:            "Audit Logs",
    sessions:             "Sessions",
    lockedAccountsTab:    "Locked Accounts",
    overviewTab2:         "Overview",
    resolve:              "Resolve",
    unlock:               "Unlock",
    terminate:            "Terminate",
    lowSev:               "Low",
    mediumSev:            "Medium",
    highSev:              "High",
    criticalSev:          "Critical",
    allSeverities:        "All Severities",
    noEvents:             "No security events",
    noAuditLogs:          "No audit logs",
    noSessions:           "No active sessions",
    noLockedAccounts:     "No locked accounts",
    resolved:             "Resolved",
    unresolved:           "Open",
    loginAttempts:        "Login Attempts",
    successful:           "Successful",
    failedLabel:          "Failed",
    uniqueIPs:            "Unique IPs",
    last24h:              "Last 24 Hours",
    topIPs:               "Top IPs",
    recentFails:          "Recent Failures",
    device:               "Device",
    lastActive:           "Last Active",
    attempts:             "attempts",
    failures:             "failures",

    // ── Security extra ───────────────────────────────────────────────────────
    openEvents7d:         "Open Incidents (7d)",
    lockedAccountsLabel:  "Locked Accounts",
    activeSessions1h:     "Active Sessions (1h)",
    activeProtectionLayers: "Active Protection Layers",
    protectionFeatures: [
      "Password Encryption (bcrypt 12 rounds)",
      "IP Block after 20 failed attempts",
      "Account Lock after 5 attempts",
      "Security Headers (Helmet.js)",
      "Rate Limiting (500 req/15min)",
      "CSRF Protection (SameSite + Origin Check)",
      "Session Expiration (8 hours)",
      "Audit Log for all operations",
      "Tenant Isolation (company_id)",
      "SQL Injection Prevention (Drizzle ORM)",
      "XSS Prevention (Input Sanitization)",
      "Device Tracking & Session Management",
    ],
    loginStats:           "Login Statistics",
    successfulTotal:      "Successful (total)",
    failedTotal:          "Failed (total)",
    topIPs24h:            "Top IPs by login attempts (24h)",
    requests:             "req",
    noRecords:            "No records found",
    successLabel:         "Success",
    resolveEvent:         "Resolve",
    terminateSession:     "Terminate",
    unlockAccount:        "Unlock",
    failedAttempts:       "failed attempts",
    lockedUntil:          "Locked until",
    activeSessions2:      "Active Sessions",
    lockedAccountsTitle:  "Locked Accounts",
    superAdmin:           "Super Admin",
    roleAdmin:            "Admin",
    roleManager:          "Manager",
    roleEmployee:         "Employee",
    password:             "Password",
    supportCenter:        "Support Center",
    roleCol:              "Role",
    downloadBackup:       "Download",
    deleteBackup:         "Delete",
    confirmDelete:        "Confirm Delete",
    confirmDeleteMsg:     "Are you sure you want to delete",
    confirmDeleteData:    "All associated data will be deleted.",
    toggleStatus:         "Toggle Status",
    editLabel:            "Edit",
    deleteLabel:          "Delete",
    addNewCompany:        "Add New Company",
    companyAdminData:     "Company Admin Details",
    fullName:             "Full Name *",
    createCompanySubmit:  "Create Company",
    newPasswordLabel:     "New Password",
    changePasswordTitle:  "Change Password for",
    changePasswordSubmit: "Change",
  },
} as const;

export type SALang = "ar" | "en";
export type SAKey = keyof typeof SA_T.ar;

export function saT(lang: SALang, key: SAKey): string {
  return (SA_T[lang] as Record<string, string>)[key] ?? (SA_T.ar as Record<string, string>)[key] ?? key;
}

// ─── Theme-aware color palette for super-admin pages ───────────────────────
export interface SAColors {
  pageBg:          string;
  headerBg:        string;
  headerBorder:    string;
  cardBg:          string;
  cardBorder:      string;
  textPrimary:     string;
  textSecondary:   string;
  textMuted:       string;
  tableRowAlt:     string;
  tableRowHover:   string;
  tableBorder:     string;
  inputBg:         string;
  inputBorder:     string;
  inputText:       string;
  modalBg:         string;
  modalBorder:     string;
}

export function getSAColors(isDark: boolean): SAColors {
  if (isDark) {
    return {
      pageBg:        "linear-gradient(135deg,#020817,#050d1f,#080318)",
      headerBg:      "rgba(2,8,23,0.9)",
      headerBorder:  "rgba(255,255,255,0.08)",
      cardBg:        "rgba(255,255,255,0.03)",
      cardBorder:    "rgba(255,255,255,0.07)",
      textPrimary:   "#ffffff",
      textSecondary: "rgba(255,255,255,0.55)",
      textMuted:     "rgba(255,255,255,0.3)",
      tableRowAlt:   "rgba(255,255,255,0.01)",
      tableRowHover: "rgba(255,255,255,0.03)",
      tableBorder:   "rgba(255,255,255,0.04)",
      inputBg:       "rgba(255,255,255,0.05)",
      inputBorder:   "rgba(255,255,255,0.1)",
      inputText:     "#ffffff",
      modalBg:       "#0d1526",
      modalBorder:   "rgba(255,255,255,0.1)",
    };
  }
  return {
    pageBg:        "linear-gradient(135deg,#f0f4f8,#e8eef6,#f4f0fa)",
    headerBg:      "rgba(255,255,255,0.97)",
    headerBorder:  "rgba(0,0,0,0.08)",
    cardBg:        "#ffffff",
    cardBorder:    "#e2e8f0",
    textPrimary:   "#0f172a",
    textSecondary: "#475569",
    textMuted:     "#94a3b8",
    tableRowAlt:   "#f8fafc",
    tableRowHover: "#f1f5f9",
    tableBorder:   "#e2e8f0",
    inputBg:       "#f8fafc",
    inputBorder:   "#cbd5e1",
    inputText:     "#0f172a",
    modalBg:       "#ffffff",
    modalBorder:   "#e2e8f0",
  };
}
